version: '3'

services:
  douyin:
    build: ./
    container_name: douyin
    restart: always
    environment:
      VIDEO_BUCKET: video-douyin #自定义
      OSS_END_POINT: oss-cn-hangzhou.aliyuncs.com #自定义
      OSS_ACCESS_KEY_ID: LTAI5tFEgYiCBYLE6Ro8JqBR #自定义，已禁用
      OSS_ACCESS_KEY_SECRET: tCFXk3dIC0KQ6UNLc9fanVrTa9YAq9 #自定义，已禁用
      OSS_VIDEO_URL_PREFIX: https://video-douyin.oss-cn-hangzhou.aliyuncs.com/ #自定义
      HOST_IP: 47.103.0.144 #自定义, 别攻击我，信任大家
    expose:
      - 8080
    ports:
      - 9000:8080
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --default-time_zone='+8:00'
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: douyin
    volumes:
      - /Users/duxinhao/Desktop/douyin/db/sql:/docker-entrypoint-initdb.d
      - /var/lib/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 5000:3306

  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - /usr/local/redis:/usr/local/redis
    expose:
      - 6379
    ports:
      - 6000:6379
